name: "Setup Sanitized Qt"
description: "Install a sanitizer-enabled Qt build"

inputs:
  qt-tag:
    description: "Qt tag or sha1 to download, e.g., v6.11.0-beta2"
    required: true
  qt-flavor:
    description: "Sanitizer/build variant: asan, ubsan, tsan, debug, or profile"
    required: true

outputs:
  qt-path:
    description: "Full path to the Qt installation root"
    value: ${{ steps.setup-qt.outputs.qt-path }}

runs:
  using: composite
  steps:
    - name: Install QtGui dependencies
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y \
          build-essential libgl1-mesa-dev libgstreamer-gl1.0-0 \
          libpulse-dev libxcb-glx0 libxcb-icccm4 libxcb-image0 \
          libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
          libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 \
          libxcb-util1 libxcb-xfixes0 libxcb-xinerama0 libxcb1 \
          libxkbcommon-dev libxkbcommon-x11-0 libxcb-xkb-dev \
          libxcb-cursor0

    - name: Checkout CI tools
      uses: actions/checkout@v4
      with:
        repository: KDABLabs/ci-release-tools
        path: ci-release-tools
        ref: main

    - name: Setup Sanitized Qt
      id: setup-qt
      shell: bash
      run: |
        ./ci-release-tools/src/build_qt/ci-download-qt.sh qt-${{ inputs.qt-tag }}-${{ inputs.qt-flavor }}
        echo "$HOME/Qt/qt-${{ inputs.qt-tag }}-${{ inputs.qt-flavor }}/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/Qt/qt-${{ inputs.qt-tag }}-${{ inputs.qt-flavor }}/lib/" >> $GITHUB_ENV
        echo "qt-path=$HOME/Qt/qt-${{ inputs.qt-tag }}-${{ inputs.qt-flavor }}" >> $GITHUB_OUTPUT
